import { Task, WeeklyVelocity } from './types';

export const INITIAL_TASKS: Task[] = [
  {
    id: '1',
    uid: 'demo-user',
    title: 'Facade Blueprint Review',
    description: 'Reviewing load-bearing specs for glass walls.',
    duration: '2h 30m',
    due: 'Oct 24, 4:00 PM',
    priority: 'High',
    status: 'Pending',
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    uid: 'demo-user',
    title: 'Site Ventilation Analysis',
    duration: '1h 15m',
    due: 'Oct 25, 11:00 AM',
    priority: 'Medium',
    status: 'Pending',
    createdAt: Date.now() - 90000,
  },
  {
    id: '3',
    uid: 'demo-user',
    title: 'Structural Integrity Test',
    duration: '3h 00m',
    due: 'Oct 24, 2:00 PM',
    priority: 'High',
    status: 'In Progress',
    progress: 65,
    createdAt: Date.now() - 80000,
  },
  {
    id: '4',
    uid: 'demo-user',
    title: 'Client Portfolio Update',
    duration: '45m',
    due: 'Oct 26, 10:00 AM',
    priority: 'Low',
    status: 'Pending',
    createdAt: Date.now() - 70000,
  },
  {
    id: '5',
    uid: 'demo-user',
    title: 'Drafting: North Wing Elevation',
    description: 'Reviewing load-bearing specs for glass walls.',
    duration: '2h 00m',
    due: 'Oct 24, 11:00 AM',
    priority: 'High',
    status: 'In Progress',
    progress: 45,
    startTime: '09:00 AM',
    endTime: '11:00 AM',
    createdAt: Date.now() - 60000,
  },
  {
    id: '6',
    uid: 'demo-user',
    title: 'Vendor Coordination Call',
    duration: '1h 15m',
    due: 'Oct 24, 2:15 PM',
    priority: 'Medium',
    status: 'Completed',
    startTime: '01:00 PM',
    endTime: '02:15 PM',
    createdAt: Date.now() - 50000,
  }
];

export const VELOCITY_DATA: WeeklyVelocity[] = [
  { day: 'MON', done: 85, remaining: 15 },
  { day: 'TUE', done: 60, remaining: 40 },
  { day: 'WED', done: 95, remaining: 5 },
  { day: 'THU', done: 40, remaining: 60 },
  { day: 'FRI', done: 100, remaining: 0 },
];
